# Generated by Django 3.2.7 on 2021-10-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
