# Generated by Django 3.2.7 on 2021-10-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0002_alter_alojamiento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='imagen',
            field=models.ImageField(upload_to='alojamientos'),
        ),
    ]
