# Generated by Django 3.2.7 on 2021-10-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0002_alojamiento_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='domingoAbrir',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='domingoCerrar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='juevesAbrir',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='juevesCerrar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='lunesAbrir',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='lunesCerrar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='martesAbrir',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='martesCerrar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='miercolesAbrir',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='miercolesCerrar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='sabadoAbrir',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='sabadoCerrar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='viernesAbrir',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='viernesCerrar',
            field=models.IntegerField(null=True),
        ),
    ]
