# Generated by Django 3.2.7 on 2021-10-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0003_auto_20211026_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='abrir',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='cerrar',
            field=models.DateTimeField(null=True),
        ),
    ]
