# Generated by Django 3.2.7 on 2021-10-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0004_auto_20211006_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
