# Generated by Django 3.2.7 on 2021-10-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0005_auto_20211026_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamiento',
            name='domingoAbrir',
        ),
        migrations.RemoveField(
            model_name='alojamiento',
            name='domingoCerrar',
        ),
        migrations.RemoveField(
            model_name='alojamiento',
            name='juevesAbrir',
        ),
        migrations.RemoveField(
            model_name='alojamiento',
            name='juevesCerrar',
        ),
        migrations.RemoveField(
            model_name='alojamiento',
            name='lunesAbrir',
        ),
        migrations.RemoveField(
            model_name='alojamiento',
            name='lunesCerrar',
        ),
        migrations.RemoveField(
            model_name='alojamiento',
            name='martesAbrir',
        ),
        migrations.RemoveField(
            model_name='alojamiento',
            name='martesCerrar',
        ),
        migrations.RemoveField(
            model_name='alojamiento',
            name='miercolesAbrir',
        ),
        migrations.RemoveField(
            model_name='alojamiento',
            name='miercolesCerrar',
        ),
        migrations.RemoveField(
            model_name='alojamiento',
            name='sabadoAbrir',
        ),
        migrations.RemoveField(
            model_name='alojamiento',
            name='sabadoCerrar',
        ),
        migrations.RemoveField(
            model_name='alojamiento',
            name='viernesAbrir',
        ),
        migrations.RemoveField(
            model_name='alojamiento',
            name='viernesCerrar',
        ),
    ]
