# Generated by Django 3.2.7 on 2021-10-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0005_alter_alojamiento_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
    ]
