# Generated by Django 3.2.7 on 2021-10-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0006_auto_20211027_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
    ]
