# Generated by Django 3.2.7 on 2021-10-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
    ]
