# Generated by Django 3.2.7 on 2021-10-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_usuario', models.IntegerField(choices=[[0, 'Alojamiento'], [1, 'Experiencia'], [2, 'Gastronomia'], [3, 'Servicio'], [4, 'Tienda']])),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
            ],
        ),
    ]
